### ISSUE TITLE
Release for Noetic / Foxy 

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/radar_msgs#7]

**Comment by SteveMacenski** [comment]
Foxy is blocked by uuid_msgs not being released

**Comment by icolwell-as** [comment]
Hi @SteveMacenski, Is there anything I can do to help get these messages out on Noetic?
We are hoping to release our Delphi ESR driver on Noetic.

**Comment by SteveMacenski** [comment]
@icolwell-as We can do that, the `master` branch is for ROS2 (CI and all setup for Foxy). I setup a Noetic branch https://github.com/ros-perception/radar_msgs/tree/noetic. If you had some cycles to update the CMakeLists/Package.xml/CircleCI container to Noetic, I'll run a release the same day

I also renamed master to `ros2` to make that clear. Right now that branch couldn't be released for noetic since the build tool / Ci won't build for it

**Comment by icolwell-as** [comment]
Perfect! thanks for laying it out, I hope to get started by the end of the week.

**Comment by SteveMacenski** [comment]
Awesome, I'd usually just do it myself since its only a little work but I'm really slammed with other maintenance tasks and if I added this to my queue, it might be on the order of months before it would get done.

**Comment by SteveMacenski** [comment]
Noetic release in progress

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/28524

**Comment by Aposhian** [comment]
Is there anything still blocking the foxy release? It looks like we have `ros-foxy-unique-identifier-msgs`

**Comment by SteveMacenski** [comment]
Will do today

**Comment by SteveMacenski** [comment]
in progress, release to be submitted in a few minutes
